### ISSUE TITLE
scheduled event data access/logging

### ISSUE THREAD

**Issue by adamwilbert** [dougmoscrop/serverless-http#104]
I am using scheduled events, in addition to normal http requests served through serverless-http, but I don't seem to have access to logging or anything else when the event fires.

For example:
```
      - schedule:
          name: ${self:service}-${self:provider.stage}-func-warmer
          rate: rate(5 minutes)
          enabled: true
          input:
            warmer: true
            concurrency: 1
```
with an immediate `console.log(req, res, next)` in the handler results in logging through cloudwatch similar to 

```
START RequestId:  Version: $LATEST
END RequestId: 
REPORT RequestId: 	Duration: 1.61 ms	Billed Duration: 100 ms 	Memory Size: 1024 MB	Max Memory Used: 92 MB
```

Any thoughts on why that might be?
