### ISSUE TITLE
Feature request: Support for AWS API Gateway payload version 2

### ISSUE THREAD

**Issue by danyfedorov** [dougmoscrop/serverless-http#146]
Link with info about version 1 vs version 2.

https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html

**Comment by mpvosseller** [comment]
If useful to others: until payload version 2 is supported we can get this to work by specifying version 1 like this:
```yml
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      # ...
      Events:
        Http:
          Type: HttpApi
          Properties:
            PayloadFormatVersion: '1.0'
```

**Comment by TehNrd** [comment]
This is the file that needs changes, ya? https://github.com/dougmoscrop/serverless-http/blob/master/lib/provider/aws/create-request.js

If someone can confirm, I can take a stab at this.

**Comment by TehNrd** [comment]
I believe the example from @mpvosseller above is for [SAM](https://github.com/awslabs/aws-sam-cli).

If using the [serverless](https://github.com/serverless/serverless) framework, the following is a workaround:

```yaml
resources:
  Resources:
    Overrides:
      Type: AWS::ApiGatewayV2::ApiGatewayManagedOverrides
      Properties: 
        ApiId: 
          Ref: "HttpApi"
        Integration: 
          PayloadFormatVersion: '1.0'
```

**Comment by Frans-L** [comment]
@TehNrd 

With your workaround, I got an error:  ```The CloudFormation template is invalid: Template format error: Unresolved resource dependencies [HttpApi] in the Resources block of the template```

Do you have any guess how this could be solved?

**Comment by TehNrd** [comment]
What does the rest of your serverless.yml file look like?

**Comment by TehNrd** [comment]
@Frans-L What does the rest of your serverless.yml file look like?

**Comment by Frans-L** [comment]
@TehNrd 

Thanks for helping out. Here is the whole serverless.yml

```yml
service:
  name: test

app: something-test
org: something

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-3
  apiGateway:
    minimumCompressionSize: 1024
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

functions:
  app:
    handler: src/app.handler
    events:
      - http: ANY /
      - http: "ANY /{proxy+}"
```
