### ISSUE TITLE
Response body breaks with cors middlewares usage.

### ISSUE THREAD

**Issue by niteshgrg** [dougmoscrop/serverless-http#151]
Response body which is a valid json becomes something of sort. WHile using with serverless cors:true and cors middleware.

"HTTP/1.1 201 OK
X-Powered-By: Express
Access-Control-Allow-Origin: *
Content-Type: application/json; charset=utf-8
Content-Length: 979
ETag: W/"3d3-lsMbiatDuk11/kGt2lF+ji87gW8"
Date: Sun, 19 Apr 2020 06:07:04 GMT
Connection: keep-alive

{..json }"

**Comment by hkyq** [comment]
Getting this even without CORS. Server:

```js
import serverless from 'serverless-http'
import express from 'express'

const app = express();


app.get('/', async (req, res) => {
  res.send("hello world")
})

export const main = serverless(app);
```

```
functions:
  server:
    handler: dist/server.main
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
```

First request is normal, then it returns the headers like above.

**Comment by dougmoscrop** [comment]
What versions of everything?

**Comment by Fatxx** [comment]
I'm facing a similar issue, in development and at the first request the body is a well-formatted json after that it seems to add the headers into the response body.

![Screenshot 2020-04-29 at 10 12 43](https://user-images.githubusercontent.com/575479/80579787-84c08a80-8a02-11ea-945d-b9f170d12519.png)

As you can see the headers seem to be added to the response body somehow which invalidates the JSON body:

![Screenshot 2020-04-29 at 10 12 09](https://user-images.githubusercontent.com/575479/80579793-8722e480-8a02-11ea-8930-854f89261a82.png)

I'm using just a simple expressjs endpoint which returns an object:

```javascript
const app = express();
app.use(express.json({ limit: '10mb' }));
app.post('/validate-license', async (req, res) => {
 return res.send({id: "", key: "", ...})
})
```

**Comment by Fatxx** [comment]
I tried this with versions 2.3.2 and 2.0.0

**Comment by mark-carrington** [comment]
Is there any update on this issue? I'm seeing this with the following versions:
serverless: 1.67.3
serverless-http: 2.3.2

I also noticed this occurring without CORS. I tried stripping the code right back to the following (and still saw the issue):

```
import serverless from 'serverless-http'
import express from 'express'

const app = express()
app.get('/news', (req, res) => res.status(200).json({“message”: “hello world"})

const handler = serverless(app)
module.exports.handler = async (event, context) => {
  const result = await handler(event, context)
  return result
}
```

With the following serverless.yml:

```
provider:
  name: aws
  runtime: nodejs12.x

functions:
    app:
        handler: src/app.handler
        events:
            - http:
                  path: /
                  method: get
                  private: true
            - http:
                  path: /{proxy+}
                  method: get
                  private: true
    getNews:
        handler: src/app.handler
        events:
            - http:
                  path: /news/{proxy+}
                  method: get
                  private: true

```
