### ISSUE TITLE
Serverless Integration Option Support

### ISSUE THREAD

**Issue by ricxsar** [dougmoscrop/serverless-http#23]
Hi. Do you have any plans on supporting lambda integration? I would like to use the User Pool as my authentication of the API and I need to specify the integration type as `lambda` to use the User Pool claims.

Here is my partial `serverless.yml` definition.
```
functions:

  # Test API
  test:
    handler: handler.main
    events:
      - http:
          path: / # this matches the base path
          method: ANY
          integration: lambda
          authorizer:
            arn: ${self:custom.userPoolARN}
            claims:
              - custom:organization
              - cognito:groups
      - http:
          path: /{any+} # this matches any path, the token 'any' doesn't mean anything special
          method: ANY
          integration: lambda
          authorizer:
            arn: ${self:custom.userPoolARN}
            claims:
              - custom:organization
              - cognito:groups
```
Here is my handler file.
```
'use strict';

import serverless from 'serverless-http';
import express from 'express';

const app = express()

app.get('/', function (req, res) {
  res.send('Hello World!')
})

module.exports.main = serverless(app);
```
When I try to deploy it using the above configuration, the following output is return on the API Gateway.
```
{"statusCode":404,"headers":{"x-powered-by":"Express","content-security-policy":"default-src 'self'","x-content-type-options":"nosniff","content-type":"text/html; charset=utf-8","content-length":155},"body":"<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<title>Error</title>\n</head>\n<body>\n<pre>Cannot GET [object%20Object]</pre>\n</body>\n</html>\n"}
```
