### ISSUE TITLE
`req.status(400).json({ message: 'some custom error' })` not working with LAMBDA_PROXY integration

### ISSUE THREAD

**Issue by shierro** [dougmoscrop/serverless-http#97]
Hi!

Please correct me if i understand it wrong. As i understand, if we use `LAMBDA_PROXY` APIG integration, we will be able to send custom error messages from lambda. 

So i have tried to use 
`req.status(400).json({ message: 'email address taken' })`

but to have my API return
```html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Error</title>
    </head>
    <body>
        <pre>Bad Request</pre>
    </body>
</html>
```
with status code 400(got this right)

I remember overcoming this issue before, but is a big wall for me now. I hope someone can help.

Thanks!

**Comment by dougmoscrop** [comment]
This looks like some kind of middleware or misconfiguration

For sanity check:

- just set up a simple Lambda that returns hardcoded { response .. } type stuff
- get rid of all middleware

**Comment by shierro** [comment]
@dougmoscrop sort of, i think i might have messed up something, on how I registered the last middleware(err handler)

can you take a peak?
https://stackoverflow.com/questions/56429705/send-custom-error-message-with-serverless-http-express

for quick ref:
```javascript
const register = async (req, res, next) {
  try {
    await verifyEmail(req.body.email);
    const user = await Users.register(req.body);
    const token = sign(user.attrs, {});
    res.json({ token, user });
  } catch (e) {
    next(e);
  }
};

const generalError = async (err, req, res, next) => {
  // doesn't reach this part! :(
  console.log('generalError handler', JSON.stringify(err));
  res.status(errorOut.status).json(errorOut);
};

ApiRouter.post('/register', register);
app.use('/auth', ApiRouter);
app.use(generalError);
```
serverless.yml
```yml
functions:
  auth:
    handler: src/express/auth/index.handler
    name: ${self:service}-auth-${env:STAGE}
    # warmup: true
    integration: lambda-proxy
    memorySize: 128
    timeout: 15
    events:
        - http:
            path: /auth/
            method: ANY
            cors: true
        - http:
            path: /auth/{any+}
            method: ANY
            cors: true
        - http:
            path: /auth/
            method: OPTIONS
            cors: true
            contentHandling: CONVERT_TO_TEXT
        - http:
            path: /auth/{any+}
            method: OPTIONS
            cors: true
            contentHandling: CONVERT_TO_TEXT
```
